### PR TITLE
Add Travis CI config

### PR DESCRIPTION
**Pull request by tjwallace**
@tobami you will have to enable builds yourself here: https://travis-ci.org/profile

### CODE REVIEW

**Comment by tjwallace** [comment]
Probably have to add `before_install: gem install chef`

**Comment by tjwallace** [comment]
@thekorn do you have permissions to enable travis builds?

**Comment by tobami** [comment]
@tjwallace  done. Build fails, can you have a look at it please?: #22

**Comment by tjwallace** [comment]
@tobami thanks! I'll take a look at the failures.

**Pull request merged**
