### PR TITLE
support whyrun mode

### LINKED ISSUE #49: Treetop not loaded with chef-solo and --why-run
When I try to run a recipe that depends on chef-solo-search on an omnibus Chef 11.8.0 install using "chef-solo ... -W", I get the following error.  When I remove the "-W", it works.

```
Starting Chef Client, version 11.8.0
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef-solo/cvl-chef/cookbooks/chef-solo-search/libraries/search.rb
================================================================================


LoadError
---------
cannot load such file -- treetop


Cookbook Trace:
---------------
  /var/chef-solo/cvl-chef/cookbooks/chef-solo-search/libraries/vendor/chef/solr_query/query_transform.rb:18:in `<top (required)>'
  /var/chef-solo/cvl-chef/cookbooks/chef-solo-search/libraries/search/parser.rb:20:in `<top (required)>'
  /var/chef-solo/cvl-chef/cookbooks/chef-solo-search/libraries/search.rb:41:in `<top (required)>'


Relevant File Content:
----------------------
/var/chef-solo/cvl-chef/cookbooks/chef-solo-search/libraries/vendor/chef/solr_query/query_transform.rb:

 11:  #
 12:  # Unless required by applicable law or agreed to in writing, software
 13:  # distributed under the License is distributed on an "AS IS" BASIS,
 14:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 15:  # See the License for the specific language governing permissions and
 16:  # limitations under the License.
 17:  #
 18>> require 'treetop'
 19:  require 'chef/solr_query/lucene_nodes'
 20:  
 21:  class Chef
 22:    class Exceptions
 23:      class QueryParseError < StandardError
 24:      end
 25:    end
 26:  end
 27:  
```

### PR DESCRIPTION
**Pull request by michaelglass**
need to test, but this should fix #49

### CODE REVIEW

**Comment by tobami** [comment]
Cool. Got an idea how to test this?

**Comment by michaelglass** [comment]
I think I'll just stub that codepath after trying it by hand.

**Comment by tobami** [comment]
Yeah, sounds good.

**Comment by michaelglass** [comment]
added tests but don't have a nice test run to ensure it actually works.  @crawley do you mind taking a stab at manually testing this?

**Comment by michaelglass** [comment]
gonna merge this and re-open if it is a problem later.  mildly cowboy but don't like keeping prs open this long.

**Pull request merged**
