### PR TITLE
Pull request for issue 54

### PR DESCRIPTION
**Pull request by duallain**
for #54

### CODE REVIEW

**Comment by michaelglass** [comment]
this repo is so simple I'm not particularly averse to this solution.  Can you add one unit test that simply ensures there are no subdirectories of library, else this changeset will likely die.

**Comment by michaelglass** [comment]
just dropping a reference to https://github.com/opscode/chef/pull/760/ (thanks @miah)

**Comment by duallain** [comment]
I have never written tests in ruby before.  Please take a look and let me know if there is a better way to do this test, better place to put it, etc. 

Thank you.

**Comment by michaelglass** [comment]
merged with a slight change to the tests and some history cleanup. See changes here: 3791086

**Comment by michaelglass** [comment]
#56.  need to fix that and to add a regression test for this to be merged.

**Pull request closed without merging**
