### PR TITLE
Search encrypted databags fix

### PR DESCRIPTION
**Pull request by daften**
Writing tests to finish #71.
However, there were no tests for encrypted data bags, and I can't find documentation on how to use secure data bags the way the current tests use regular data bags.
And the current secure data bags don't seem to be in the right format, the new ones have a iv key as well for extra security.

Any feedback is welcome!

### CODE REVIEW

**Comment by daften** [comment]
No feedback? :s

**Comment by michaelglass** [comment]
this project has been mostly abandoned due to chef zero. Are you interested in becoming a maintainer?

**Comment by daften** [comment]
I didn't know it was abandoned. I don't think chef-zero can be used e.g. with knife-solo to bootstrap a single server. How chef zero could replace chef solo for something like that, I don't see that. :s

**Comment by michaelglass** [comment]
https://github.com/higanworks/knife-zero

**Comment by rtheobald** [comment]
Be that as it may, but I'm not in a position to move yet, and this fix was just what I needed to get by until I do. Cheers!

**Comment by daften** [comment]
FYI: I have also moved to chef-zero and abandoned chef-solo-search now. I'll leave this PR, but at some point, I might delete my fork :)

**Pull request closed without merging**
